name: GitHub Actions
run-name: PR Github Actions triggered by ${{ github.actor }}
on: [pull_request]
jobs:
  convert_knapsack_json_to_amplience:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }}"
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Get committed files
        id: get_commit_data
        run: committed_files="$(git diff --name-status HEAD^ HEAD)"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Running script
        run: npm run patrick
        id: get_return_value
      - name: Output results
        run: |
          echo "The output value is ${{ steps.get_return_value.outputs.my_output }}"
          echo "Job status: ${{ job.status }}."
