name: GitHub Actions
run-name: PR Github Actions triggered by ${{ github.actor }}
on: [pull_request]
jobs:
  convert_knapsack_json_to_amplience:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }}"
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Echo changed files
        run: echo "$(git diff --name-status origin/main..HEAD)"
      - name: Echo github.event
        run: echo "JSON.stringify(${{ github.event }})"
      - name: Get committed files
        id: get_commit_data
        run: echo "committed_files='$(gh pr view ${PR_NUMBER} --json baseRefName,headRefName,body,files)'" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Running script
        id: process_committed_files
        run: npm run convert-for-amplience
        env:
          COMMITTED_FILES: ${{ steps.get_commit_data.outputs.committed_files }}
      - name: Output results
        run: |
          echo "The output value is ${{ steps.process_committed_files.outputs.results }}"
          echo "Job status: ${{ job.status }}."
